name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npx eslint *.js --max-warnings 0
    
    - name: Run Prettier check
      run: npx prettier --check "*.js" "*.json" "*.md"
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level=moderate
    
    - name: Validate package.json
      run: |
        node -e "const pkg = require('./package.json'); if (!pkg.engines || !pkg.engines.node) throw new Error('Missing node engine requirement');"
        
    - name: Test module imports
      run: |
        node -e "import('./capture-and-timelapse.js').catch(e => { if (!e.message.includes('UNIFI_HOST')) throw e; })"
        node -e "import('./setup.js').catch(e => {})"
        node -e "import('./status.js').catch(e => {})"
