name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint *.js --max-warnings 0

      - name: Run Prettier check
        run: npx prettier --check "*.js" "*.json" "*.md"

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate

      - name: Validate package.json
        run: |
          node -e "const pkg = require('./package.json'); if (!pkg.engines || !pkg.engines.node) throw new Error('Missing node engine requirement');"

      - name: Test module syntax
        run: |
          # Just verify the modules have valid syntax, don't actually run them
          node --check capture-and-timelapse.js
          node --check lawn-lapse.js

      - name: Test basic imports
        run: |
          # Test that the main module exports the expected functions
          node -e "
            import('./lawn-lapse.js').then(module => {
              const required = ['runSetup', 'runCapture', 'runStatus', 'loadExistingConfig', 'saveConfig'];
              const missing = required.filter(fn => !module[fn]);
              if (missing.length > 0) {
                throw new Error('Missing exports: ' + missing.join(', '));
              }
              console.log('✓ All expected functions are exported');
            }).catch(e => {
              console.error('Failed to import lawn-lapse.js:', e.message);
              process.exit(1);
            });
          "
